version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:16-alpine
    container_name: arrowtower-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-arrowtower}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js 应用
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arrowtower-app
    restart: unless-stopped
    ports:
      - "30000:3000"
    environment:
      # 数据库连接
      DATABASE_URL: ${DATABASE_URL}

      # NextAuth 配置
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

      # Web3 / 区块链配置
      PRIVATE_KEY: ${PRIVATE_KEY}
      NEXT_PUBLIC_MINTER_CONTRACT: ${NEXT_PUBLIC_MINTER_CONTRACT}
      NEXT_PUBLIC_NFT_ADDRESS: ${NEXT_PUBLIC_NFT_ADDRESS}
      CHAIN_ID: ${CHAIN_ID}
      RPC_URL: ${RPC_URL}
      NETWORK: ${NETWORK}

      # 其他环境变量
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local