name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'

env:
  NODE_VERSION: '20'

jobs:
  # 检测是否有实际代码变更
  changes:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'app/**'
              - 'components/**'
              - 'lib/**'
              - 'prisma/**'
              - 'public/**'
              - 'package*.json'
              - 'next.config.*'
              - 'tsconfig.json'

  quality-check:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - run: npx prisma generate
      - run: npm run lint
        continue-on-error: true
      - run: npx tsc --noEmit
        continue-on-error: true
      - run: npm test --if-present
        continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    environment: delpoy
    needs: [changes, quality-check]
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push' &&
      needs.changes.outputs.should_deploy == 'true'
    steps:
      - name: Trigger Coolify webhook
        run: |
          response=$(curl --request GET '${{ secrets.COOLIFY_WEBHOOK_URL }}' \
            --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}' \
            --write-out '%{http_code}' \
            --silent \
            --output /dev/null)
          
          if [ "$response" -eq 200 ] || [ "$response" -eq 201 ]; then
            echo "✅ Deployment webhook triggered successfully"
          else
            echo "❌ Deployment webhook failed with status: $response"
            exit 1
